name: minter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  http: ^0.13.4
  web_socket_channel: ^2.1.0
  dart_web3: ^0.0.3
  fluttertoast: ^8.0.8
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - src/artifacts/Minter.json
    - assets/images/crypto.jpg